### PR TITLE
Add summary section to announcement templates

### PR DESCRIPTION
**Pull request by josiah-wolf-oberholtzer**
Per-request on the sc-user mailing list, we should include the executive summary of the RFC in the announcement templates.

### CODE REVIEW

**Review by mossheim — APPROVED** [review]
thanks!

**Comment by josiah-wolf-oberholtzer** [comment]
@brianlheim Feel free to merge. I don't have write access.

**Comment by mossheim** [comment]
waiting for nathan to give it a look :)

**Review by nhthn — APPROVED** [review]

**Comment by nhthn** [comment]
pleased to announce that i have " given it a look "

**Pull request merged**
