### PR TITLE
License the content in the repository under the terms of the CC-BY-SA-4.0

### PR DESCRIPTION
**Pull request by dvzrv**
Hi! I noticed that the existing content is not licensed, which can become problematic in the future.

It might be a good idea to hold off on merging further RFCs until this is resolved.

### CODE REVIEW

**Comment by dvzrv** [comment]
To be able to license existing works it is necessary to get the permission from @nhthn @brianlheim @josiah-wolf-oberholtzer and @telephon who have thus far contributed to this repository.
NOTE: This is the basis upon which any additional work can be licensed under the terms of the CC-BY-SA-4.0, unless we would like to add exemptions per file (which is a lot of work to track).

An answer to this pull request in the form of "I consent to my existing work on the SuperCollider RFC repository to be licensed under the terms of the CC-BY-SA-4.0." should suffice.
In case you can or want to provide cryptographic proof for that message (e.g. by providing a PGP signed message), that is of course also appreciated.

**Comment by mossheim** [comment]
thanks @dvzrv !

I consent to my existing work on the SuperCollider RFC repository to be licensed under the terms of the CC-BY-SA-4.0.

And I support this RFC. For what it's worth, I'd be fine with any CC license that includes the BY component. BY-SA seems like a reasonable one to me for these types of documents.

**Comment by nhthn** [comment]
I consent to my existing work on the SuperCollider RFC repository to be licensed under the terms of the CC-BY-SA-4.0.

**Comment by muellmusik** [comment]
Can someone just clarify, what exactly are we licensing here? The text of the RFCs? Code (which may end up being licensed under GPL as part of SC)? Something else?

**Comment by muellmusik** [comment]
> Can someone just clarify, what exactly are we licensing here? The text of the RFCs? Code (which may end up being licensed under GPL as part of SC)? Something else?

Oh sorry you just mean the READMEs and other stuff 'in' the repository. Sorry, long week...

**Comment by josiah-wolf-oberholtzer** [comment]
I consent to my existing work on the SuperCollider RFC repository to be licensed under the terms of the CC-BY-SA-4.0.

**Comment by dvzrv** [comment]
A friendly ping to @telephon to reply to this as well :)

**Comment by telephon** [comment]
This ping never appeared in my notifications, I don't know why. Sorry. Yes, I am fine with this change!

**Comment by dvzrv** [comment]
I have rebased and sent out the notifications for Final Comment Period.

**Pull request merged**
